Some updates

diff --git a/bash/ffmpeg_squish b/bash/ffmpeg_squish
--- a/bash/ffmpeg_squish
+++ b/bash/ffmpeg_squish
@@ -47,9 +47,16 @@ function run_ffmpeg {
 	CONVERT_TO_MONO_AUDIO="-ac 1"
 	SCALE_VIDEO="-filter:v scale=480:-1"
 	OVERWRITE_OUTPUT_FILE_IF_EXISTS="-y"
-	CMD="ffmpeg -i $1 $CONVERT_TO_MONO_AUDIO $SCALE_VIDEO $OVERWRITE_OUTPUT_FILE_IF_EXISTS $2"
+	ONLY_DISPLAY_PANIC_MESSAGES="-loglevel panic"
+	CMD="ffmpeg -i \"$INPUT_FILE\" $CONVERT_TO_MONO_AUDIO $SCALE_VIDEO $OVERWRITE_OUTPUT_FILE_IF_EXISTS $ONLY_DISPLAY_PANIC_MESSAGES \"$OUTPUT_FILE\""
 	echo "Executing $CMD"
-	#eval $CMD
+	eval $CMD
+
+	if [ "$?" -ne 0 ] ; then
+		echo "Warning: ffmpeg returned an error, conversion has most likely failed"
+	fi
+
+	echo -e "\nffmpeg execution is now complete."
 }
 
 
@@ -59,7 +66,9 @@ function send_optional_notification {
 		echo "'FFMPEG_SQUISH_WEBHOOK' environment variable is not set, skipping sending Slack notification that this script has completed."
 		return
 	fi
-	curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"ffmpeg_squish has completed producing $1\"}" $FFMPEG_SQUISH_WEBHOOK
+
+	OUTPUT_FILE="'"$1"'"
+	curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"ffmpeg_squish has completed producing $OUTPUT_FILE\"}" $FFMPEG_SQUISH_WEBHOOK
 	if [ "$?" -ne 0 ] ; then
 		echo "Warning: Failed to send Slack notification"
 	fi
@@ -78,13 +87,13 @@ function main {
 	verify_arguments "$NUMBER_OF_ARGS" "$INPUT_FILE" "$OUTPUT_FILE"
 
 	# Invoke ffmpeg
-	run_ffmpeg $INPUT_FILE $OUTPUT_FILE
+	run_ffmpeg "$INPUT_FILE" "$OUTPUT_FILE"
 
 	# Send optional notification
-	send_optional_notification $OUTPUT_FILE
+	send_optional_notification "$OUTPUT_FILE"
 }
 
 
 ## Trigger this script
 main "$#" "$1" "$2"
-
+echo -e "\n"
